# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-03 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preference',
            field=models.CharField(choices=[('All', 'All'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Technology', 'Technology'), ('Movies', 'Movies'), ('Vehicle', 'Vehicles')], default='all', max_length=10),
        ),
    ]
